name: taga_cuyo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # API
  http: ^1.2.2

  # Firebase 
  firebase_database: ^11.1.6
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4

  # Bloc
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  


  # Design
  curved_navigation_bar: ^1.0.6
  flutter_carousel_widget: ^3.1.0
  lottie: ^3.2.0
  
  # freezed_annotation: ^2.4.4
  # json_annotation: ^4.9.0
  # freezed: ^2.5.7
  image_picker: ^1.1.2
  meta: ^1.15.0
  auto_route: ^9.2.2
  build_runner: ^2.4.13
  firebase_storage: ^12.4.0
  device_info_plus: ^11.2.0
  path_provider: ^2.1.5
  dio: ^5.7.0
  shared_preferences: ^2.4.0
  cached_network_image: ^3.4.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.0
  firebase_auth_platform_interface: 
  firebase_core_platform_interface: 
  mocktail: 
  plugin_platform_interface:
  auto_route_generator: ^9.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/Logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/LogoRound.png"
  
flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/images/Logo.png
    - assets/animation/loadingsplash.json
    - assets/animation/booksplash.json
    - assets/animation/confetti.json



  fonts:
    - family: LilitaOne
      fonts:
        - asset: assets/fonts/LilitaOne-Regular.ttf
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Light.ttf
    - family: Roboto-Regular
      fonts: 
        - asset:  assets/fonts/Roboto-Regular.ttf
    - family: FER
      fonts: 
        - asset:  assets/fonts/Fredoka_Expanded-Regular.ttf
    - family: FCB
      fonts: 
        - asset:  assets/fonts/Fredoka_Condensed-Bold.ttf
    - family: FEB
      fonts: 
        - asset:  assets/fonts/Fredoka_Expanded-Bold.ttf
    - family: FCR
      fonts: 
        - asset:  assets/fonts/Fredoka_Condensed-Regular.ttf
